volumes:
  postgres-data:
    external: true

  pg-admin:
    external: true

services:

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_MEALMATE_API: http://localhost:8000

  postgres:
    build:
      context: ./db
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=mealmate
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: mm15@mm15.com
      PGADMIN_DEFAULT_PASSWORD: mm15
      PGADMIN_DISABLE_POSTFIX: 1

  mealmate:
    build:
      context: ./mealmate
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./mealmate:/app
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_URL: postgresql://mealmate:password@postgres/mealmate
      WAIT_HOSTS: postgres:5432
      PORT: 8000
