volumes:
  postgres-data:
    external: true

services:

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_MEALMATE_API: http://localhost:8000

  postgres:
    image: postgres:14.2-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mealmates
      - POSTGRES_USER=mealmates
      - POSTGRES_PASSWORD=password
    ports:
      - 15432:5432

  mealmate-service:
    build:
      context: ./mealmate-service
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./mealmate-service:/app
    depends_on:
      - postgres
    environment:
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_URL: postgresql://mealmates:password@postgres/mealmates
      WAIT_HOSTS: postgres:5432
