from queries.pool import pool

# chef photo urls
# https://static8.depositphotos.com/1377527/955/i/450/depositphotos_9551898-stock-photo-head-shot-of-chef.jpg
# https://i.pinimg.com/236x/a5/4e/e3/a54ee32ff16ae7e3c298eaca2bb6a825.jpg
# https://www.thecourieronline.co.uk/wp-content/uploads/2021/10/IMG_2785-1024x673.jpg


def load_data():
    try:
        with pool.connection() as conn:
            with conn.cursor() as cur:
                cur.execute(
                    """
                    insert into roles (name) values ('subscriber');
                    insert into roles (name) values ('chef');
                    insert into users (first_name, last_name, username, email, hashed_password, picture_url, role_id) values ('John', 'Doe', 'johndoe', 'johndoe@gmail.com', 'password', 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8YXZhdGFyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=900&q=60', 1);
                    insert into users (first_name, last_name, username, email, hashed_password, picture_url, role_id) values ('Jane', 'Doe', 'janedoe', 'janedoe@gmail.com', 'password', 'https://districtfray.com/wp-content/uploads/2023/03/Ria-Montes-Headshot1-1.jpg', 2);
                    insert into users (first_name, last_name, username, email, hashed_password, picture_url, role_id) values ('Joe', 'Doe', 'joedoe', 'joedoe@gmail.com', 'password', 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8YXZhdGFyfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=900&q=60', 1);
                    insert into users (first_name, last_name, username, email, hashed_password, picture_url, role_id) values ('Jill', 'Doe', 'jilldoe', 'jilldoe@gmail.com', 'password', 'https://i.pinimg.com/736x/cd/a2/a2/cda2a2c9e23b631814dda8ea5ea4e073--corporate-headshots-headshot-ideas.jpg', 2);
                    insert into statuses (name) values ('pending');
                    insert into statuses (name) values ('completed');
                    insert into statuses (name) values ('cancelled');

                    insert into meals (chef_id, name, name2, calories, is_keto, is_vegan, is_chef_choice, is_spicy, has_cheese, picture_url, description, ingredients) values 
                    (2,'Pesto Salmon', 'with Creamed Spinach & Tomato Butter Haricots Verts', 700, true, false, true, false, false, 'https://img.hellofresh.com/w_1200,q_auto,f_auto,c_limit,fl_lossy/q_auto/recipes/image/640b6cea8fbd1f824e04997b-2071566c.jpg','Get your greens—and all of the feel-good benefits that go along with them—with this pescatarian dish. Here, oven-roasted salmon is served on a bed of velvety creamed spinach made with cream cheese, Parmesan, onions, and garlic. A blanket of vibrant kale pesto adds another layer of green goodness on top. For textural contrast, crisp haricots verts (aka slender green beans) with sun-dried tomato and basil butter complete the meal.','Ingredients: Salmon, Spinach, Haricots Verts, Cream Cheese (Pasteurized Milk And Cream, Cheese Culture, Salt, Guar Gum, Carob Bean Gum, Xanthan Gum), Olive Pomace Oil, Onions, Unsalted Butter (Pasteurized Cream, Natural Flavorings), Shredded Parmesan Cheese (Parmesan Cheese (Pasteurized Part-Skim Milk, Cheese Culture, Salt, Enzymes), Powdered Cellulose To Prevent Caking, Natamycin To Protect Flavor), Garlic, Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Almonds, Baby Kale, Basil, Spinach, Sun-Dried Tomatoes (Sun-Dried Tomatoes, Salt), Sea Salt, Granulated Garlic'); 
                    insert into meals (chef_id, name, name2, calories, is_keto, is_vegan, is_chef_choice, is_spicy, has_cheese, picture_url, description, ingredients) values
                    (4,'Chicken Tikka Masala', 'with Basmati Rice, Chickpeas & Curry Cauliflower', 490, false, false, true, true, true, 'https://img.hellofresh.com/w_1200,q_auto,f_auto,c_limit,fl_lossy/q_auto/recipes/image/640b7b6fe0314bf19203476d-3ea62b2b.jpg', 'Classic Indian-inspired flavors are on full display with this creamy chicken dish. Tender marinated chicken is slathered in our fragrant tikka masala sauce that has chock-full of spices, heavy cream, and cream cheese. It’s garnished with scallions and cilantro and served alongside seasoned basmati rice, masala-spiced chickpeas, and curry-spiced cauliflower florets.','Ingredients: Chicken Breast, Cauliflower, Water, Chickpeas (Prepared Chickpeas Beans, Water, Salt, Disodium Edta To Promote Color Retention), Heavy Cream, Onions, Concentrated Crushed Tomatoes (Tomatoes, Salt), Lowfat Buttermilk (Cultured Lowfat Milk, Nonfat Dry Milk, Salt, Sodium Citrate, Vitamin A Palmitate And Vitamin D3), Tomato Paste (Tomatoes, Citric Acid), Tomatoes, White Basmati Rice, Garlic, Ginger, Brown Basmati Rice, Cream Cheese (Pasteurized Milk And Cream, Cheese Culture, Salt, Guar Gum, Carob Bean Gum, Xanthan Gum), Green Onions, Olive Pomace Oil, Roasted Chicken Stock Base (Chicken Stock, Roasted Chicken Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks, Dried Chicken Stock, Salt, Gelatin, Water, White Wine)), Plain Greek Yogurt (Pasteurized Cow’S And Goat’S Milk, Skim Milk, Milk Protein Concentrate, Cream, Contains Active Cultures Including L. Acidophilus, B. Lactis), Cilantro, Cumin Seeds, Sea Salt, Coriander, Curry Powder (Coriander, Fenugreek, Fennel, Mustard, Turmeric, Cumin, Black Pepper, Bay Leaves, Celery Seed, Nutmeg, Cloves, Onion, Red Pepper, Ginger, Chile Powder, Cinnamon, Cardamon, Salt), Turmeric, Paprika (Paprika And Silicon Dioxide (Added To Make Free Flowing)), Chili Powder (Chili Pepper, Spices, Salt, Garlic Powder), Black Pepper, Cinnamon, Cloves, Nutmeg, Ground Fennel, Ground Bay Leaves, Fenugreek Leaves');
                    insert into meals (chef_id, name, name2, calories, is_keto, is_vegan, is_chef_choice, is_spicy, has_cheese, picture_url, description, ingredients) values
                    (2,'Spicy Sweet Potatoes & Peanut Sauce','with Coconut Rice & Miso-Roasted Green Beans', 660, false, true, true, true, false, 'https://img.hellofresh.com/w_1080,q_auto,f_auto,c_limit,fl_lossy/q_auto/recipes/image/641891d2b786533ae4097582-65d3880d.jpg', 'Sweet, savory, and spicy flavors are on full display in this Indonesian-inspired vegan dish. We start with tender roasted sweet potatoes and drape them in a traditional satay sauce made with peanut butter, ginger, garlic, lime juice, and sambal chili sauce for a spicy kick. It’s all piled over coconut basmati rice, and garnished with toasted peanuts that are spiced with gogucharu (Korean chili flakes). On the side there’s green beans, roasted with red miso, sesame, and roasted garlic for a hit of umami.','Ingredients: Sweet Potatoes, Green Beans, Water, Brown Basmati Rice, Peanut Butter, Garlic, Ginger, Roasted Peanuts, Olive Pomace Oil, Unsweetened Coconut Milk (Coconut, Water, Guar Gum), Cilantro, Blue Agave Nectar, Lime Juice, Coconut Aminos (Organic Coconut Nectar, Organic Pure Coconut Blossom Sap, Natural Unrefined Sea Salt (Less Than 2%)), Red Miso Paste (Filtered Water, Cultured Rice, Organic Whole Soy Beans, Sea Salt), Toasted Sesame Oil, Gochugaru Chile Flakes, Desiccated Coconut, Sambal Oelek Chili Paste (Red Chili Peppers, Salt, Distilled Vinegar, Xanthan Gum), Ground Kaffir Lime Leaves, Sea Salt, Black Sesame Seeds, Toasted Sesame Seeds');
                    insert into meals (chef_id, name, name2, calories, is_keto, is_vegan, is_chef_choice, is_spicy, has_cheese, picture_url, description, ingredients) values
                    (4,'Spicy Poblano Beef Bowl','with Roasted Broccoli Rice & Scallion Sour Cream', 580, true, false, true, true, true, 'https://img.hellofresh.com/w_1080,q_auto,f_auto,c_limit,fl_lossy/q_auto/recipes/image/641ded0391433a6f540a71f2-2428ca5e.jpg','Enjoy spicy, bold flavors in this simple yet satisfying keto bowl. We start by simmering ground beef with cumin, chili powder, and cayenne, kick it up even more with jalapeño and poblano peppers, then sprinkle on some cheddar cheese. We’ve also added a side of broccoli “rice“ for a boost of veggies, and a drizzle of scallion sour cream to cool things off.','Ingredients: Ground Beef, Riced Broccoli, Poblano Peppers, Tomato Sauce (Tomatoes, Tomato Puree, Salt, Red Pepper, Dehydrated Bell Peppers, Dehydrated Onion, Dehydrated Garlic, Onion Powder, Garlic Powder, Spice Extractive, Citric Acid, Natural Flavoring), Sour Cream (Cultured Cream), Shredded Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Annatto Vegetable Color, Anti-Caking Agent (Potato Starch, Powdered Cellulose, Corn Starch, Natamycin)), Sliced Jalapeño Peppers (Jalapeño Peppers, Water, Distilled Vinegar, Salt, Calcium Chloride, Garlic Powder, Sodium Benzoate, Riboflavin), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Green Onions, Roasted Garlic Oil (Olive Pomace Oil, Garlic), Granulated Onion, Chili Powder (Chili Pepper, Spices, Salt, Garlic Powder), Paprika (Paprika And Silicon Dioxide (Added To Make Free Flowing)), Cumin, Sea Salt, Granulated Garlic, Black Pepper, Cayenne Pepper');
                    insert into meals (chef_id, name, name2, calories, is_keto, is_vegan, is_chef_choice, is_spicy, has_cheese, picture_url, description, ingredients) values
                    (2,'Garlic Rosemary Pork Chop', 'with Creamy Parmesan Brussels & Garlic Broccoli', 590, true, false, true, false, true, 'https://img.hellofresh.com/w_1080,q_auto,f_auto,c_limit,fl_lossy/q_auto/recipes/image/garlic-rosemary-pork-chop-w14-b79606d1.jpg', 'This indulgent dish features a garlic-rosemary grilled pork chop that has been brined with apple cider vinegar for extra tenderness. It pairs beautifully with the two vegetable sides: roasted Brussels sprouts enriched with Parmesan cream and soft garden herb cheese plus garlicky broccoli florets topped with lemon garlic butter.','Ingredients: Pork Chop, Broccoli, Brussels Sprouts, Heavy Cream, Neufchatel Cheese (Pasteurized Milk And Cream, Skim Milk, Cheese Culture, Salt, Guar Gum, Carob Bean Gum, Xanthan Gum), Unsalted Butter (Pasteurized Cream, Natural Flavorings), Grated Parmesan Cheese ((Parmesan Cheese (Pasteurized Cow’S Milk, Cheese Culture, Salt, Enzymes), Water, Milk Protein, Modified Food Starch, Palm Oil Blend, Salt, Disodium Phosphate, Citric Acid, Xanthan Gum), And Calcium Propionate (Preservative)), Olive Pomace Oil, Garlic, Sea Salt, Granulated Onion, Toasted Garlic Powder, Granulated Garlic, Apple Cider Vinegar, Thyme, Sage, Black Pepper, Toasted Minced Garlic, Rosemary, Lemon Powder (Citric Acid, Natural Lemon Flavor), Dried Parsley, Dried Dill Weed, Smoked Black Pepper (Pepper, Smoke Flavor), Dried Chives, Dried Thyme');
                    insert into meals (chef_id, name, name2, calories, is_keto, is_vegan, is_chef_choice, is_spicy, has_cheese, picture_url, description, ingredients) values
                    (4, 'Indian Butter Chicken','with Cilantro Lime Cauliflower Rice',630, true, false, true, false, false, 'https://img.hellofresh.com/w_1080,q_auto,f_auto,c_limit,fl_lossy/q_auto/recipes/image/641deee7d8a9d25cb708914f-5d54396f.jpg','This Indian-inspired meal begins with a tender bed of cauliflower “rice” enhanced with cilantro, lime juice, and garlic. It’s topped with juicy garam masala-spiced chicken, then swirled in a rich tomato-based sauce made with butter, heavy cream, cumin, coriander, chili powder and even more aromatic masala spices.','Ingredients: Chicken Breast, Riced Cauliflower, Crushed Tomatoes (Tomatoes, Tomato Puree, Less Than 2% Salt, Citric Acid), Heavy Cream, Unsalted Butter (Pasteurized Cream, Natural Flavorings), Olive Pomace Oil, Onions, Water, Roasted Garlic Oil (Olive Pomace Oil, Garlic), Plain Greek Yogurt (Pasteurized Cow’S And Goat’S Milk, Skim Milk, Milk Protein Concentrate, Cream, Contains Active Cultures Including L. Acidophilus, B. Lactis), Cilantro, Green Onions, Ginger, Garlic, Whole Milk (Pasteurized Milk, Vitamin D3), Sea Salt, Monkfruit Sweetener (Erythritol, Monk Fruit Extract), Cumin, Lime Juice, Chili Powder (Chili Pepper, Spices, Salt, Garlic Powder), Coriander, Turmeric, Black Pepper, Lime Powder (Citric Acid, Natural Lime Flavor), Cinnamon, Fenugreek Leaves, Smoked Black Pepper (Pepper, Smoke Flavor), Cloves, Nutmeg, Ground Fennel');
                    insert into meals (chef_id, name, name2, calories, is_keto, is_vegan, is_chef_choice, is_spicy, has_cheese, picture_url, description, ingredients) values
                    (2, 'Shredded Chicken Taco Bowl','with Roasted Corn Salsa & Cilantro Lime Sour Cream',530,false, false, true, false, false, 'https://img.hellofresh.com/w_1080,q_auto,f_auto,c_limit,fl_lossy/q_auto/recipes/image/641e6043383e0665f80afd5e-c7176d1e.jpg','Packed with savory Mexican-style flavors, each element of this dish comes together to form one exciting bowl. Juicy shredded chicken, seasoned with our house-made taco seasoning, is served over black beans and brown rice. It’s all accented with a roasted corn salsa made with spicy poblanos, red bell peppers, cilantro, paprika, cumin, and chili powder. The meal is finished with a creamy cilantro sour cream, perfect for drizzling over the top.','Ingredients: Chicken Breast, Yellow Sweet Corn, Water, Long Grain Parboiled Brown Rice, Sour Cream (Cultured Cream), Black Beans, Shredded Cheddar Cheese (Pasteurized Milk, Cheese Cultures, Salt, Enzymes, Annatto Vegetable Color, Anti-Caking Agent (Potato Starch, Powdered Cellulose, Corn Starch, Natamycin)), Cilantro, Poblano Peppers, Red Onions, Red Bell Peppers, Green Onions, Olive Oil, Chili Powder (Chili Pepper, Spices, Salt, Garlic Powder), Roasted Chicken Stock Base (Chicken Stock, Roasted Chicken Stock, Mirepoix Stock (Made Of Carrot, Celery And Onion Stocks, Dried Chicken Stock, Salt, Gelatin, Water, White Wine)), Lime Juice, Jalapeño Peppers, Sea Salt, Cumin, Paprika (Paprika And Silicon Dioxide (Added To Make Free Flowing)), Black Pepper, Garlic, Granulated Garlic, Crushed Red Pepper Flakes, Granulated Onion, Dried Oregano');
                    insert into meals (chef_id, name, name2, calories, is_keto, is_vegan, is_chef_choice, is_spicy, has_cheese, picture_url, description, ingredients) values
                    (4, 'Tomato & Roasted Vegetable Risotto', 'with Zucchini, Bell Peppers & Toasted Pine Nuts', 440, false, true, true, false, false, 'https://img.hellofresh.com/w_1080,q_auto,f_auto,c_limit,fl_lossy/q_auto/recipes/image/641e69c2deca2fd86f0d0421-8939fc94.jpg','Any time is a good time to savor this elegant vegan risotto. Arborio rice, red onions, and garlic are simmered in red wine, low and slow until creamy and tender, then sprinkled with basil and nutritional yeast to add a “cheesy” note. On the side: a vibrant mix of roasted bell peppers, zucchini, and cherry tomatoes, plus a serving of toasted pine nuts, which adds a light nutty crunch.','Ingredients: Water, Arborio Rice, Zucchini, Red Bell Peppers, Grape Tomatoes, Pine Nuts, Crushed Tomatoes (Tomatoes, Tomato Puree, Less Than 2% Salt, Citric Acid), Red Onions, Cabernet Sauvignon Wine (Grapes, Sulfites), Olive Pomace Oil, Nutritional Yeast Flakes (Dried Yeast, Niacin, Pyridoxine Hydrochloride (B6), Riboflavin, Thiamine Hydrochloride, (Thiamine), Folic Acid, Cobalamin (B12)), Sea Salt, Garlic, Basil, Black Pepper');

                    insert into boxes (subscriber_id) values (1);
                    insert into boxes (subscriber_id) values (3);

                    insert into box_meals (box_id, meal_id, quantity) values (1, 1, 1);
                    insert into box_meals (box_id, meal_id, quantity) values (1, 2, 1);
                    insert into box_meals (box_id, meal_id, quantity) values (2, 3, 1);
                    insert into box_meals (box_id, meal_id, quantity) values (2, 4, 1);
                    insert into orders (subscriber_id, status_id) values (1, 1);
                    insert into orders (subscriber_id, status_id) values (3, 2);
                    insert into order_meals (order_id, meal_id, quantity) values (1, 1, 1);
                    insert into order_meals (order_id, meal_id, quantity) values (1, 2, 1);
                    insert into order_meals (order_id, meal_id, quantity) values (1, 3, 1);
                    insert into order_meals (order_id, meal_id, quantity) values (2, 2, 1);
                    insert into order_meals (order_id, meal_id, quantity) values (2, 3, 1);
                    insert into order_meals (order_id, meal_id, quantity) values (2, 4, 1);
                    """
                )
                print("***********Data loaded************")
    except Exception as e:
        print(e)
        return {"message": "Data not loaded"}


if __name__ == "__main__":
    load_data()
